name: Infrastructure as Code

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy (dev, prod, etc.)'
        type: choice
        options:
          - DEV
          - prod
          - staging
        required: true
      terraform_command_type:
        description: 'Select the Terraform command to run'
        type: choice
        options:
          - plan
          - validate
          - apply -auto-approve
          - destroy -auto-approve
        required: true
permissions: write-all
jobs:
  workflow_job:
    secrets: inherit
    uses: ./.github/workflows/codedeploy.yml
    with:
      environment: ${{ inputs.environment }}
      terraform_command_type: ${{ inputs.terraform_command_type }}
