name: PR check

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format Check
        id: fmt
        run: |
          terraform fmt -check
        continue-on-error: true # Fail the workflow if this step fails

      - name: Terraform Validate
        id: validate
        run: terraform validate
        continue-on-error: true # Fail the workflow if this step fails
