name: Terraform test

on:
  push:
    branches:
      - main
    paths:
      - 'Environments/DEV/**'
      - 'Environments/UAT/**'
      - 'Environments/QA/**'
      - 'Environments/PROD/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.10.2'

      - name: Print GitHub commit SHAs
        run: |
          echo "Before Commit SHA: ${{ github.event.before }}"
          echo "Current Commit SHA: ${{ github.sha }}"

      - name: Check changed files
        run: |
          # Ensure the before commit exists, fallback to HEAD^ if not
          if [ -z "${{ github.event.before }}" ]; then
            echo "No 'before' commit found, comparing HEAD with HEAD^"
            git diff --name-only HEAD^ HEAD
          else
            echo "Comparing changes between ${GITHUB_EVENT_BEFORE} and ${GITHUB_SHA}"
            git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          fi

      - name: Check for Changes and Deploy to Environment
        run: |
          # Determine which environment has changed
          if [ -z "${{ github.event.before }}" ]; then
            changed_dir=$(git diff --name-only HEAD^ HEAD | grep -E '^Environments/(DEV|UAT|QA|PROD)/' | head -n 1)
          else
            changed_dir=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^Environments/(DEV|UAT|QA|PROD)/' | head -n 1)
          fi

          if [[ -z "$changed_dir" ]]; then
            echo "No relevant environment changes detected. Skipping deployment."
            exit 0
          fi

          # Set the environment based on the modified directory
          environment=$(echo "$changed_dir" | cut -d'/' -f2)

          echo "Changes detected in environment: $environment"

          # Map environment to the appropriate secret name
          if [ "$environment" == "DEV" ]; then
            ROLE_ARN=${{ secrets.ROLE_ARN_DEV }}
          elif [ "$environment" == "UAT" ]; then
            ROLE_ARN=${{ secrets.ROLE_ARN_UAT }}
          elif [ "$environment" == "QA" ]; then
            ROLE_ARN=${{ secrets.ROLE_ARN_QA }}
          elif [ "$environment" == "PROD" ]; then
            ROLE_ARN=${{ secrets.ROLE_ARN_PROD }}
          else
            echo "Error: Unknown environment '$environment'."
            exit 1
          fi

          echo "Assuming role: $ROLE_ARN"

          # Configure AWS credentials using GitHub OIDC
          - name: Set up AWS credentials using GitHub OIDC
            uses: aws-actions/configure-aws-credentials@v1
            with:
              role-to-assume: $ROLE_ARN
              aws-region: ap-south-1  # Replace with your region

          # Run Terraform commands for the detected environment
          cd Environments/$environment
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
